#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Dec 09, 2024 11:52:06 AM +07  platform: Windows NT

import sys
from tkinter import Toplevel
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import GUIv2
_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = GUIv2.Toplevel1(_top1)
    root.mainloop()
def popupError(message):
        global popup
        popup = Toplevel(root)
        popup.title("Thông Báo")
        popup.geometry("200x200")
        root_x = root.winfo_x()
        root_y = root.winfo_y()
        root_w = root.winfo_width()
        root_h = root.winfo_height()

        popup_w , popup_h=200,200

        x = root_x+(root_w//2)-(popup_w//2)
        y = root_y+(root_h//2)-(popup_h//2)
        popup.geometry(f"{popup_w}x{popup_h}+{x}+{y}")
        tk.Label(popup,text=message,font=("Arial",14)).pack(pady=50)

if __name__ == '__main__':
    global popup
    GUIv2.start_up()




